name: CI CD Pipeline
run-name: Automated ci trigger by ${{github.event_name}}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run math test file
        run: npx jest test/test.js

      - name: Run controller test file
        run: npx jest controllers/url.test.js
