name: CI CD Pipeline
run-name: Automated ci trigger by ${{github.event_name}}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  #NODE_ENV: production
  GLOBAL_VAR: "this is global variable"

jobs:
  Test:
    # if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # run on multiple Node versions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up Node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run math test file
        run: npm test -- test/test.js

      - name: Run controller/url test file
        run: npm test controllers/url.test.js

      - name: Run controller/user test file
        run: npm test controllers/user.test.js

  Build:
    runs-on: ubuntu-latest

    #needs: Test
    env:
      MY_API: ${{secrets.MY_API}}

    steps:
      - name: "Print Hello World"
        run: echo "Hello World from yml"

      - name: Print local Varible
        run: echo "${GLOBAL_VAR}"

      - name: "Print Secret"
        run: echo MY_API
